environment:
  matrix:
    - nodejs_version: "12"
    - nodejs_version: "11"
    - nodejs_version: "10"
    - nodejs_version: "9"
    - nodejs_version: "8"
platform:
  - x86
  - x64
services:
  - mysql
install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:PLATFORM
  - npm -v
  - node -v
  - npm install
build: off
test_script:
  - node --version
  - npm --version
  - npm run test
version: "{build}"
